[project]
name = "commander"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "pyinstaller>=6.14.0",
    "pywin32-ctypes>=0.2.3",
    "typer>=0.16.0",
]
